server:
  port: '9090'
  servlet:
    context-path: '/personigramaunibagueBackend'
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://172.19.21.11:5432/personigrama'
    username: uiperson
    password: '..'
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'